[global]

# Development mode settings
developmentMode = false

# Show warning about running on localhost
showWarningOnDirectExecution = false

# Disable file watcher for performance in production
fileWatcherType = "auto"

[server]

# Server configuration
port = 8501
baseUrlPath = ""

# Enable CORS for development
enableCORS = true
enableXsrfProtection = true

# Upload settings
maxUploadSize = 200
maxMessageSize = 200

# WebSocket settings
enableWebsocketCompression = false

[browser]

# Automatically open browser on startup
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]

# UI Theme configuration
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[logger]

# Logging configuration
level = "info"
messageFormat = "%(asctime)s %(message)s"

[client]

# Client configuration
caching = true
displayEnabled = true
showErrorDetails = true

[runner]

# Streamlit runner configuration
magicEnabled = true
installTracer = false
fixMatplotlib = true

# FastScript settings
fastReruns = true
enforceSerializableSessionState = false

[mapbox]

# Mapbox token (if needed for map components)
# token = "your_mapbox_token_here"

[deprecation]

# Deprecation warnings
showfileUploaderEncoding = false
showPyplotGlobalUse = false