version: 0.5
nodes:
  source: {}
  llm:
    agent: openAIAgent
    params:
      model: gpt-5-mini-2025-08-07
    inputs:
      prompt: :source.test2
    timeout: 200000 # milliseconds
  output:
    agent: copyAgent
    params:
      namedKey: text
    console:
      before: output start
      after: true
    inputs:
      text: :llm.text
    isResult: true
