version: '3.8'

services:
  # JobQueue Service - Job queue management API
  jobqueue:
    build:
      context: ./jobqueue
      dockerfile: Dockerfile
    container_name: myswiftagent-jobqueue
    ports:
      - "8001:8000"
    environment:
      - PYTHONPATH=/app
      - JOBQUEUE_DB_URL=sqlite+aiosqlite:///./data/jobqueue.db
      - TZ=Asia/Tokyo
    volumes:
      - jobqueue_data:/app/data
    networks:
      - myswiftagent
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  # MyScheduler Service - Job scheduling service
  myscheduler:
    build:
      context: ./myscheduler
      dockerfile: Dockerfile
    container_name: myswiftagent-myscheduler
    ports:
      - "8002:8000"
    environment:
      - PYTHONPATH=/app
      - TZ=Asia/Tokyo
      - JOBQUEUE_API_URL=http://jobqueue:8000
    depends_on:
      jobqueue:
        condition: service_healthy
    networks:
      - myswiftagent
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  # ExpertAgent Service - AI agent service
  expertagent:
    build:
      context: ./expertAgent
      dockerfile: Dockerfile
    container_name: myswiftagent-expertagent
    ports:
      - "8003:8000"
    environment:
      - PYTHONPATH=/app
      - TZ=Asia/Tokyo
      # Add your API keys here or use .env file
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
      # - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      # - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    networks:
      - myswiftagent
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  # GraphAiServer Service - Graph AI workflow service
  graphaiserver:
    build:
      context: ./graphAiServer
      dockerfile: Dockerfile
    container_name: myswiftagent-graphaiserver
    ports:
      - "8004:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - TZ=Asia/Tokyo
      # Add your API keys here or use .env file
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
      # - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    networks:
      - myswiftagent
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  # CommonUI Service - Web interface
  commonui:
    build:
      context: ./commonUI
      dockerfile: Dockerfile
    container_name: myswiftagent-commonui
    ports:
      - "8501:8000"
    environment:
      - PYTHONPATH=/app
      - TZ=Asia/Tokyo
      - JOBQUEUE_API_URL=http://jobqueue:8000
      - MYSCHEDULER_API_URL=http://myscheduler:8000
      - EXPERTAGENT_API_URL=http://expertagent:8000
      - GRAPHAISERVER_API_URL=http://graphaiserver:8000
    depends_on:
      jobqueue:
        condition: service_healthy
      myscheduler:
        condition: service_healthy
      expertagent:
        condition: service_healthy
      graphaiserver:
        condition: service_healthy
    networks:
      - myswiftagent
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    restart: unless-stopped

networks:
  myswiftagent:
    driver: bridge
    name: myswiftagent-network

volumes:
  jobqueue_data:
    name: myswiftagent-jobqueue-data
