"""Unit tests for Issue #410: user_input_schema end-to-end propagation.

This module tests that user_input_schema generated by LLM is properly
propagated through the entire system:
- JobGenerationResult (orchestrator.py)
- JobGeneratorResponse (job_generator.py)
- Adapter conversion (_convert_result)

Test Plan:
1. JobGenerationResult has user_input_schema field
2. JobGeneratorResponse has user_input_schema field
3. _convert_result propagates user_input_schema
4. _build_result sets user_input_schema from analysis
"""

from typing import Any

from aiagent.langgraph.jobGeneratorV2.nodes.job_analyzer import (
    AnalyzedTask,
    InterfaceDefinition,
    JobAnalysisResponse,
)
from aiagent.langgraph.jobGeneratorV2.orchestrator import (
    JobGenerationResult,
)
from app.schemas.job_generator import JobGeneratorResponse


class TestJobGenerationResultUserInputSchema:
    """Tests for user_input_schema field in JobGenerationResult."""

    def test_job_generation_result_has_user_input_schema_field(self) -> None:
        """JobGenerationResult should have user_input_schema field.

        AC-1: JobGenerationResult data class includes user_input_schema
        """
        result = JobGenerationResult(success=True)
        assert hasattr(result, "user_input_schema"), (
            "JobGenerationResult should have user_input_schema field"
        )

    def test_user_input_schema_default_is_none(self) -> None:
        """user_input_schema should default to None.

        AC-1: Default value is None for backward compatibility
        """
        result = JobGenerationResult(success=True)
        assert result.user_input_schema is None, (
            "user_input_schema should default to None"
        )

    def test_user_input_schema_can_be_set(self) -> None:
        """user_input_schema can be set with schema values.

        AC-1: user_input_schema field accepts dict values
        """
        schema = {
            "type": "object",
            "properties": {
                "keyword": {"type": "string"},
                "email": {"type": "string", "format": "email"},
            },
            "required": ["keyword", "email"],
        }
        result = JobGenerationResult(success=True, user_input_schema=schema)
        assert result.user_input_schema == schema
        assert "keyword" in result.user_input_schema["properties"]
        assert "email" in result.user_input_schema["properties"]


class TestJobGeneratorResponseUserInputSchema:
    """Tests for user_input_schema field in JobGeneratorResponse."""

    def test_job_generator_response_has_user_input_schema_field(self) -> None:
        """JobGeneratorResponse should have user_input_schema field.

        AC-1: JobGeneratorResponse Pydantic model includes user_input_schema
        """
        response = JobGeneratorResponse(status="success")
        assert hasattr(response, "user_input_schema"), (
            "JobGeneratorResponse should have user_input_schema field"
        )

    def test_user_input_schema_default_is_none(self) -> None:
        """user_input_schema should default to None.

        AC-1: Default value is None for backward compatibility
        """
        response = JobGeneratorResponse(status="success")
        assert response.user_input_schema is None, (
            "user_input_schema should default to None"
        )

    def test_user_input_schema_can_be_set(self) -> None:
        """user_input_schema can be set with schema values.

        AC-1: user_input_schema field accepts dict values
        """
        schema: dict[str, Any] = {
            "type": "object",
            "properties": {
                "keyword": {"type": "string"},
                "email": {"type": "string"},
            },
        }
        response = JobGeneratorResponse(status="success", user_input_schema=schema)
        assert response.user_input_schema == schema

    def test_user_input_schema_serializes_to_json(self) -> None:
        """user_input_schema should serialize properly to JSON.

        AC-1: API response can include user_input_schema in JSON format
        """
        schema: dict[str, Any] = {
            "type": "object",
            "properties": {"keyword": {"type": "string"}},
        }
        response = JobGeneratorResponse(status="success", user_input_schema=schema)
        json_data = response.model_dump()
        assert "user_input_schema" in json_data
        assert json_data["user_input_schema"] == schema


class TestAdapterConvertResultUserInputSchema:
    """Tests for user_input_schema propagation in adapter._convert_result."""

    def test_convert_result_includes_user_input_schema_on_success(self) -> None:
        """_convert_result should include user_input_schema in response.

        AC-1: When JobGenerationResult has user_input_schema,
              JobGeneratorResponse should also have it
        """
        from aiagent.langgraph.jobGeneratorV2.adapter import JobGeneratorAdapter
        from aiagent.langgraph.jobGeneratorV2.types import UnifiedTaskIdentifier

        adapter = JobGeneratorAdapter(max_retry=3)

        schema: dict[str, Any] = {
            "type": "object",
            "properties": {
                "keyword": {"type": "string"},
                "email": {"type": "string"},
            },
        }

        result = JobGenerationResult(
            success=True,
            job_id="job-123",
            job_master_id="master-123",
            task_identifiers=[
                UnifiedTaskIdentifier(task_id="task_001", task_master_id="tm-001")
            ],
            workflows={"task_001": {"workflow_name": "test"}},
            tasks=[
                AnalyzedTask(
                    task_id="task_001",
                    name="Test",
                    description="Test task",
                    task_type="test",
                    recommended_api="/api/test",
                )
            ],
            interfaces={
                "task_001": InterfaceDefinition(
                    input_schema={"type": "object"},
                    output_schema={"type": "object"},
                )
            },
            user_input_schema=schema,
        )

        response = adapter._convert_result(result, "job-123")

        assert response.status == "success"
        assert response.user_input_schema is not None, (
            "user_input_schema should be propagated to response"
        )
        assert response.user_input_schema == schema

    def test_convert_result_user_input_schema_is_none_when_not_set(self) -> None:
        """_convert_result should have None user_input_schema when not set.

        AC-1: Backward compatibility - None when not provided
        """
        from aiagent.langgraph.jobGeneratorV2.adapter import JobGeneratorAdapter
        from aiagent.langgraph.jobGeneratorV2.types import UnifiedTaskIdentifier

        adapter = JobGeneratorAdapter(max_retry=3)

        result = JobGenerationResult(
            success=True,
            job_id="job-123",
            job_master_id="master-123",
            task_identifiers=[
                UnifiedTaskIdentifier(task_id="task_001", task_master_id="tm-001")
            ],
            workflows={"task_001": {"workflow_name": "test"}},
            tasks=[
                AnalyzedTask(
                    task_id="task_001",
                    name="Test",
                    description="Test task",
                    task_type="test",
                    recommended_api="/api/test",
                )
            ],
            interfaces={
                "task_001": InterfaceDefinition(
                    input_schema={"type": "object"},
                    output_schema={"type": "object"},
                )
            },
            # user_input_schema not set
        )

        response = adapter._convert_result(result, "job-123")

        assert response.status == "success"
        assert response.user_input_schema is None


class TestBuildResultUserInputSchema:
    """Tests for user_input_schema in _build_result method."""

    def test_build_result_sets_user_input_schema_from_analysis(self) -> None:
        """_build_result should set user_input_schema from JobAnalysisResponse.

        AC-1: user_input_schema from analysis is propagated to result
        """

        from aiagent.langgraph.jobGeneratorV2.orchestrator import (
            JobGenerationOrchestrator,
        )
        from aiagent.langgraph.jobGeneratorV2.types import (
            ParallelExecutionResult,
            TaskResult,
            UnifiedTaskIdentifier,
        )

        orchestrator = JobGenerationOrchestrator()

        user_input_schema: dict[str, Any] = {
            "type": "object",
            "properties": {
                "keyword": {"type": "string"},
                "email": {"type": "string"},
            },
        }

        analysis = JobAnalysisResponse(
            tasks=[
                AnalyzedTask(
                    task_id="task_001",
                    name="Test",
                    description="Test",
                    task_type="test",
                    recommended_api="/api/test",
                )
            ],
            interfaces={
                "task_001": InterfaceDefinition(
                    input_schema={"type": "object"},
                    output_schema={"type": "object"},
                )
            },
            user_input_schema=user_input_schema,
        )

        registration = {"job_master_id": "master-123"}

        identifiers = [
            UnifiedTaskIdentifier(task_id="task_001", task_master_id="tm-001")
        ]

        workflow_result = ParallelExecutionResult(
            successful_tasks=[
                TaskResult(
                    task_id="task_001",
                    success=True,
                    workflow={"workflow_name": "test"},
                )
            ],
            failed_tasks=[],
            total_execution_time_ms=100.0,
        )

        result = orchestrator._build_result(
            analysis, registration, identifiers, workflow_result
        )

        assert result.success is True
        assert result.user_input_schema is not None, (
            "_build_result should set user_input_schema from analysis"
        )
        assert result.user_input_schema == user_input_schema

    def test_build_result_user_input_schema_empty_when_analysis_has_none(
        self,
    ) -> None:
        """_build_result should handle empty user_input_schema from analysis.

        AC-1: Backward compatibility when analysis has empty schema
        """
        from aiagent.langgraph.jobGeneratorV2.orchestrator import (
            JobGenerationOrchestrator,
        )
        from aiagent.langgraph.jobGeneratorV2.types import (
            ParallelExecutionResult,
            TaskResult,
            UnifiedTaskIdentifier,
        )

        orchestrator = JobGenerationOrchestrator()

        analysis = JobAnalysisResponse(
            tasks=[
                AnalyzedTask(
                    task_id="task_001",
                    name="Test",
                    description="Test",
                    task_type="test",
                    recommended_api="/api/test",
                )
            ],
            interfaces={},
            user_input_schema={},  # Empty schema
        )

        registration = {"job_master_id": "master-123"}
        identifiers = [
            UnifiedTaskIdentifier(task_id="task_001", task_master_id="tm-001")
        ]
        workflow_result = ParallelExecutionResult(
            successful_tasks=[
                TaskResult(
                    task_id="task_001",
                    success=True,
                    workflow={"workflow_name": "test"},
                )
            ],
            failed_tasks=[],
            total_execution_time_ms=100.0,
        )

        result = orchestrator._build_result(
            analysis, registration, identifiers, workflow_result
        )

        # Empty dict is converted to None or remains empty
        assert result.user_input_schema is None or result.user_input_schema == {}
