version: 0.5
nodes:
  source: {}
  # REQUIRED: Empty source node receives user_input from API request
  # user_input contains: audio_file_path, user_email, file_name

  # Step 1: Build email generation prompt using stringTemplateAgent
  # This is MANDATORY because we have multiple :source fields in a multi-line string
  build_email_prompt:
    agent: stringTemplateAgent
    inputs:
      audio_file_path: :source.audio_file_path
      user_email: :source.user_email
      file_name: :source.file_name
    params:
      template: |-
        あなたはプロフェッショナルなメール文面生成エージェントです。
        以下の情報を基に、ユーザーに送信するパーソナライズされたメールの件名と本文を生成してください。

        # 入力情報
        - ユーザーメールアドレス: ${user_email}
        - ポッドキャスト音声ファイル名: ${file_name}
        - 音声ファイルパス: ${audio_file_path}

        # タスク説明
        Task 003で生成された音声ファイルをアップロードしました。
        このメールでは、ユーザーに対してポッドキャストの生成完了を通知し、
        音声ファイルへのアクセス情報を提供してください。

        # 制約条件
        - メール件名は簡潔で、ユーザーの関心を引くものにすること
        - メール本文は親切で、次のステップを明確に示すこと
        - ファイル名をメール本文に含めること
        - 日本語で出力すること
        - 出力は RESPONSE_FORMAT に従うこと。返却は JSON 形式で行い、コメントやマークダウンは含めないこと

        # RESPONSE_FORMAT:
        {
          "subject": "メールの件名",
          "body": "メールの本文（ファイル名やURLを含む）"
        }

  # Step 2: Generate email content using expertAgent jsonoutput API via fetchAgent
  generate_email:
    agent: fetchAgent
    inputs:
      url: http://localhost:8104/aiagent-api/v1/aiagent/utility/jsonoutput
      method: POST
      body:
        user_input: :build_email_prompt
        model_name: gemini-2.5-flash
    timeout: 60000
    # CRITICAL: 60 second timeout for LLM calls (MANDATORY)

  # Step 3: Format final output with all required fields
  output:
    agent: copyAgent
    inputs:
      result:
        success: true
        subject: :generate_email.result.subject
        body: :generate_email.result.body
        user_email: :source.user_email
        error_message: ""
    isResult: true
    # REQUIRED: isResult: true marks this as the final output node
