version: 0.5
nodes:
  # Source node - receives user_input with storage_path
  source: {}

  # Step 1: Build email composition prompt
  build_email_prompt:
    agent: stringTemplateAgent
    inputs:
      storage_path: :source.storage_path
    params:
      template: |-
        あなたはプロフェッショナルなメール作成の専門家です。
        以下の要件に基づいて、ポッドキャスト共有用のメールを作成してください。

        ポッドキャスト公開リンク: ${storage_path}

        # 制約条件
        - ユーザーへの感謝のメッセージを含めること
        - ポッドキャストの簡潔な紹介（2-3文）を含めること
        - 公開リンクをクリック可能なHTML形式で記載すること
        - メール本文はHTML形式にすること
        - 温かみのあるプロフェッショナルなトーンにすること
        - 日本語で出力すること
        - 出力は RESPONSE_FORMAT に従うこと。返却は JSON 形式で行い、コメントやマークダウンは含めないこと

        # RESPONSE_FORMAT:
        {
          "subject": "メール件名",
          "body_html": "HTML形式のメール本文"
        }

  # Step 2: Generate email content
  generate_email_content:
    agent: fetchAgent
    inputs:
      url: http://localhost:8104/aiagent-api/v1/aiagent/utility/jsonoutput
      method: POST
      body:
        user_input: :build_email_prompt
        model_name: gemini-2.5-flash
    timeout: 60000

  # Step 3: Format final output
  output:
    agent: copyAgent
    inputs:
      result:
        success: true
        subject: :generate_email_content.result.subject
        body_html: :generate_email_content.result.body_html
        error_message: ""
    isResult: true
