version: 0.5
nodes:
  # Source node - receives user_input with file_name and storage_type
  source: {}

  # Step 1: Build prompt for generating public share link
  build_prompt:
    agent: stringTemplateAgent
    inputs:
      file_name: :source.file_name
      storage_type: :source.storage_type
    params:
      template: |-
        あなたはファイル共有サービスの公開リンク生成システムです。
        以下の情報を基に、公開共有リンクを生成してください。

        ファイル名: ${file_name}
        ストレージタイプ: ${storage_type}

        # 制約条件
        - ストレージタイプに応じた適切なURL形式を使用すること
        - GDRIVE: Google Driveの共有リンク形式（https://drive.google.com/file/d/XXXXX/view）
        - S3: AWS S3のパブリックURL形式（https://bucket-name.s3.region.amazonaws.com/XXXXX）
        - BLOB_STORAGE: Azure Blob Storageの形式（https://account.blob.core.windows.net/container/XXXXX）
        - ユニークなIDを含めること
        - 日本語で出力すること
        - 出力は RESPONSE_FORMAT に従うこと。返却は JSON 形式で行い、コメントやマークダウンは含めないこと

        # RESPONSE_FORMAT:
        {
          "success": true,
          "public_url": "https://example.com/share/unique_id_12345",
          "error_message": ""
        }

  # Step 2: Generate public share link
  generate_link:
    agent: fetchAgent
    inputs:
      url: http://localhost:8104/aiagent-api/v1/aiagent/utility/jsonoutput
      method: POST
      body:
        user_input: :build_prompt
        model_name: gemini-2.5-flash
    timeout: 60000

  # Step 3: Format final output
  output:
    agent: copyAgent
    inputs:
      result:
        success: :generate_link.result.success
        public_url: :generate_link.result.public_url
        error_message: :generate_link.result.error_message
    isResult: true