"""Contract tests for expertAgent <-> graphAiServer compatibility.

Issue #359 Iteration 2 Task 3.4: Contract Test implementation.

These tests verify that:
1. TaskFlow JSON generated by expertAgent is valid for graphAiServer
2. Schema changes are detected before deployment
3. API contracts between services are maintained
"""

import json

import pytest

from aiagent.langgraph.jobGeneratorV2.workflows.workflow_gen.schemas.taskflow_schema import (
    TaskFlowStep,
    TaskFlowWorkflow,
    UnifiedStepConfig,
)


class TestTaskFlowSchemaContract:
    """Contract tests for TaskFlow JSON schema."""

    def test_workflow_has_required_fields(self):
        """TaskFlow workflow must have all required fields for graphAiServer."""
        required_fields = [
            "workflow_name",
            "input_schema",
            "output_schema",
            "steps",
            "output",
        ]

        # Create a minimal valid workflow
        workflow = TaskFlowWorkflow(
            workflow_name="test_workflow",
            input_schema='{"query": "string"}',
            output_schema='{"result": "string"}',
            steps=[
                TaskFlowStep(
                    id="step_001",
                    type="api_rest",
                    config=UnifiedStepConfig(
                        step_type="api_rest",
                        method="GET",
                        url="https://api.example.com/test",
                    ),
                )
            ],
            output='{"result": "${step_001.output}"}',
        )

        workflow_dict = workflow.model_dump()

        for field in required_fields:
            assert field in workflow_dict, f"Missing required field: {field}"

    def test_step_structure_matches_graphaiserver_expectation(self):
        """Step structure must match graphAiServer expectations."""
        step = TaskFlowStep(
            id="step_001",
            type="api_rest",
            config=UnifiedStepConfig(
                step_type="api_rest",
                method="POST",
                url="https://api.example.com/endpoint",
                headers={"Content-Type": "application/json"},
                body='{"key": "value"}',
            ),
        )

        step_dict = step.model_dump()

        # Required step fields
        assert "id" in step_dict
        assert "type" in step_dict
        assert "config" in step_dict

        # Config must have step_type
        assert "step_type" in step_dict["config"]
        assert step_dict["config"]["step_type"] == "api_rest"

    def test_api_rest_config_fields(self):
        """api_rest config must have required fields for graphAiServer."""
        config = UnifiedStepConfig(
            step_type="api_rest",
            method="POST",
            url="https://api.example.com/endpoint",
        )

        config_dict = config.model_dump(exclude_none=True)

        # Required for api_rest
        assert "method" in config_dict
        assert "url" in config_dict
        assert config_dict["method"] in ["GET", "POST", "PUT", "DELETE", "PATCH"]

    def test_transform_config_fields(self):
        """transform config must have required fields for graphAiServer."""
        config = UnifiedStepConfig(
            step_type="transform",
            mode="template",
            template="${step_001.output.data}",
        )

        config_dict = config.model_dump(exclude_none=True)

        # Required for transform
        assert "mode" in config_dict
        assert config_dict["mode"] in ["template", "concat", "map", "merge"]


class TestTaskFlowVariableContract:
    """Contract tests for TaskFlow variable references."""

    def test_variable_reference_format(self):
        """Variable references must use ${...} format."""
        # This is the contract format expected by graphAiServer
        valid_references = [
            "${inputs.query}",
            "${step_001.output}",
            "${step_001.output.data}",
            "${secrets.api_key}",
        ]

        import re
        pattern = re.compile(r"\$\{[a-zA-Z_][a-zA-Z0-9_]*(\.[a-zA-Z_][a-zA-Z0-9_]*)*\}")

        for ref in valid_references:
            assert pattern.match(ref), f"Invalid reference format: {ref}"

    def test_inputs_reference_contract(self):
        """inputs references must follow ${inputs.field} pattern."""
        workflow = TaskFlowWorkflow(
            workflow_name="test",
            input_schema='{"query": "string"}',
            output_schema='{"result": "string"}',
            steps=[
                TaskFlowStep(
                    id="step_001",
                    type="transform",
                    config=UnifiedStepConfig(
                        step_type="transform",
                        mode="template",
                        template="${inputs.query}",
                    ),
                )
            ],
            output='{"result": "${step_001.output}"}',
        )

        # Should be valid - inputs.query references input_schema.query
        assert workflow.steps[0].config.template == "${inputs.query}"

    def test_step_output_reference_contract(self):
        """Step output references must follow ${step_id.output} pattern."""
        workflow = TaskFlowWorkflow(
            workflow_name="test",
            input_schema='{}',
            output_schema='{"result": "string"}',
            steps=[
                TaskFlowStep(
                    id="fetch_data",
                    type="api_rest",
                    config=UnifiedStepConfig(
                        step_type="api_rest",
                        method="GET",
                        url="https://api.example.com",
                    ),
                ),
                TaskFlowStep(
                    id="process_data",
                    type="transform",
                    config=UnifiedStepConfig(
                        step_type="transform",
                        mode="template",
                        template="${fetch_data.output}",
                    ),
                ),
            ],
            output='{"result": "${process_data.output}"}',
        )

        # Step references should use step id
        assert "${fetch_data.output}" in workflow.steps[1].config.template


class TestTaskFlowJSONSerializationContract:
    """Contract tests for JSON serialization compatibility."""

    def test_workflow_serializes_to_valid_json(self):
        """Workflow must serialize to valid JSON for graphAiServer."""
        workflow = TaskFlowWorkflow(
            workflow_name="test_workflow",
            description="Test description",
            input_schema='{"query": "string"}',
            output_schema='{"result": "string"}',
            steps=[
                TaskFlowStep(
                    id="step_001",
                    type="api_rest",
                    config=UnifiedStepConfig(
                        step_type="api_rest",
                        method="GET",
                        url="https://api.example.com/test",
                    ),
                )
            ],
            output='{"result": "${step_001.output}"}',
        )

        # Must serialize without errors
        json_str = workflow.to_json()
        assert isinstance(json_str, str)

        # Must be valid JSON
        parsed = json.loads(json_str)
        assert isinstance(parsed, dict)

    def test_workflow_deserializes_from_json(self):
        """Workflow must deserialize from JSON."""
        json_str = '''
        {
            "workflow_name": "test_workflow",
            "input_schema": "{\\"query\\": \\"string\\"}",
            "output_schema": "{\\"result\\": \\"string\\"}",
            "steps": [
                {
                    "id": "step_001",
                    "type": "api_rest",
                    "config": {
                        "step_type": "api_rest",
                        "method": "GET",
                        "url": "https://api.example.com/test"
                    }
                }
            ],
            "output": "{\\"result\\": \\"${step_001.output}\\"}"
        }
        '''

        workflow = TaskFlowWorkflow.from_json(json_str)

        assert workflow.workflow_name == "test_workflow"
        assert len(workflow.steps) == 1


class TestGraphAiServerCompatibility:
    """Contract tests for graphAiServer specific requirements."""

    def test_workflow_name_pattern(self):
        """Workflow name must match graphAiServer naming requirements."""
        # Valid patterns
        valid_names = [
            "search_gmail",
            "send_email_notification",
            "process_data_v2",
            "_internal_workflow",
        ]

        for name in valid_names:
            workflow = TaskFlowWorkflow(
                workflow_name=name,
                input_schema='{}',
                output_schema='{}',
                steps=[
                    TaskFlowStep(
                        id="step_001",
                        type="api_rest",
                        config=UnifiedStepConfig(
                            step_type="api_rest",
                            method="GET",
                            url="https://api.example.com",
                        ),
                    )
                ],
                output='{}',
            )
            assert workflow.workflow_name == name

    def test_step_id_pattern(self):
        """Step IDs must match graphAiServer naming requirements."""
        valid_ids = [
            "step_001",
            "fetch_data",
            "process_results",
            "_internal_step",
        ]

        for step_id in valid_ids:
            step = TaskFlowStep(
                id=step_id,
                type="api_rest",
                config=UnifiedStepConfig(
                    step_type="api_rest",
                    method="GET",
                    url="https://api.example.com",
                ),
            )
            assert step.id == step_id

    def test_https_enforcement(self):
        """External URLs must use HTTPS."""
        # HTTPS should be allowed
        config = UnifiedStepConfig(
            step_type="api_rest",
            method="GET",
            url="https://api.example.com/endpoint",
        )
        assert config.url == "https://api.example.com/endpoint"

        # HTTP to external should be rejected
        with pytest.raises(ValueError, match="HTTPS"):
            UnifiedStepConfig(
                step_type="api_rest",
                method="GET",
                url="http://external-api.example.com/endpoint",
            )

    def test_localhost_http_allowed(self):
        """HTTP is allowed for localhost (development)."""
        config = UnifiedStepConfig(
            step_type="api_rest",
            method="GET",
            url="http://localhost:8000/api",
        )
        assert config.url == "http://localhost:8000/api"


class TestExpertAgentOutputContract:
    """Contract tests for expertAgent output format."""

    def test_generated_workflow_structure(self):
        """expertAgent generated workflows must have correct structure."""
        from aiagent.langgraph.jobGeneratorV2.types_v3 import UnifiedTaskIdentifier

        # Simulate what expertAgent produces
        task = UnifiedTaskIdentifier(task_id="task_001", task_master_id="tm_001")

        # The workflow output should have these characteristics
        sample_workflow = {
            "workflow_name": f"workflow_{task.task_id}",
            "input_schema": '{"data": "object"}',
            "output_schema": '{"result": "object"}',
            "steps": [
                {
                    "id": "fetch",
                    "type": "api_rest",
                    "config": {
                        "step_type": "api_rest",
                        "method": "GET",
                        "url": "https://api.example.com/data",
                    }
                }
            ],
            "output": '{"result": "${fetch.output}"}',
        }

        # Should be parseable by TaskFlowWorkflow
        workflow = TaskFlowWorkflow(**sample_workflow)
        assert workflow.workflow_name == "workflow_task_001"

    def test_task_id_to_workflow_name_mapping(self):
        """Task IDs should map consistently to workflow names."""
        from aiagent.langgraph.jobGeneratorV2.types_v3 import UnifiedTaskIdentifier

        tasks = [
            UnifiedTaskIdentifier(task_id="task_001", task_master_id="tm_001"),
            UnifiedTaskIdentifier(task_id="task_002", task_master_id="tm_002"),
        ]

        # Workflow names should be derivable from task_id
        for task in tasks:
            expected_workflow_name = f"workflow_{task.task_id}"
            assert expected_workflow_name.startswith("workflow_")
            assert task.task_id in expected_workflow_name
