#!/bin/bash
# scripts/setup-worktree.sh
# Worktree自動セットアップスクリプト（空きポート検出方式 + myVault/langfuse柔軟配置）
#
# Usage:
#   cd ~/MySwiftAgent-worktrees/feature-issue-126
#   ~/MySwiftAgent/scripts/setup-worktree.sh
#
# Features:
#   - 空きポート自動検出・割り当て
#   - myVault/langfuse の配置パターン選択（共有/独立/カスタム）
#   - .env シンボリックリンク作成

set -e

WORKTREE_DIR=$(pwd)
WORKTREE_NAME=$(basename "$WORKTREE_DIR")

# メインリポジトリのパスを取得（worktree対応）
# worktreeの場合、--git-common-dirで共有.gitディレクトリのパスを取得し、その親がメインリポジトリ
GIT_COMMON_DIR=$(git rev-parse --git-common-dir 2>/dev/null || echo "")
if [ -n "$GIT_COMMON_DIR" ] && [ "$GIT_COMMON_DIR" != ".git" ]; then
    # worktreeの場合（.git/worktrees/xxx のようなパス）
    MAIN_REPO=$(cd "$GIT_COMMON_DIR/.." && pwd)
else
    # 通常のリポジトリの場合
    MAIN_REPO=$(git rev-parse --show-toplevel 2>/dev/null || echo "$HOME/MySwiftAgent")
fi

echo "📍 Setting up worktree: $WORKTREE_NAME"
echo ""

# .env.local が既に存在する場合は再実行しない
if [ -f .env.local ]; then
    echo "⚠️  .env.local already exists. Skipping setup."
    echo "   If you want to regenerate, delete .env.local first:"
    echo "   rm .env.local && ~/MySwiftAgent/scripts/setup-worktree.sh"
    exit 0
fi

# 全worktreeから使用中のインデックスを収集
echo "🔍 Detecting used worktree indices..."
USED_INDICES=()

# MySwiftAgent-worktrees ディレクトリ内の全worktreeをスキャン
WORKTREES_DIR="$(dirname "$WORKTREE_DIR")"
if [ -d "$WORKTREES_DIR" ]; then
    for worktree in "$WORKTREES_DIR"/*/; do
        if [ -f "${worktree}.env.local" ]; then
            # .env.local から WORKTREE_INDEX を抽出
            INDEX=$(grep "^WORKTREE_INDEX=" "${worktree}.env.local" 2>/dev/null | cut -d'=' -f2)
            if [ -n "$INDEX" ]; then
                USED_INDICES+=($INDEX)
            fi
        fi
    done
fi

# 使用中のインデックスをソート
if [ ${#USED_INDICES[@]} -gt 0 ]; then
    USED_INDICES=($(printf '%s\n' "${USED_INDICES[@]}" | sort -n | uniq))
fi

# 空いている最小のインデックスを検索（1から順に）
WORKTREE_INDEX=1
for used in "${USED_INDICES[@]}"; do
    if [ "$WORKTREE_INDEX" -eq "$used" ]; then
        WORKTREE_INDEX=$((WORKTREE_INDEX + 1))
    else
        break
    fi
done

echo "✅ Assigned index: $WORKTREE_INDEX"
if [ ${#USED_INDICES[@]} -gt 0 ]; then
    echo "   Used indices: ${USED_INDICES[@]}"
else
    echo "   Used indices: none (this is the first worktree)"
fi

# ポート番号を計算
BASE_EXPERTAGENT=8104
BASE_MYVAULT=8103
BASE_MYSCHEDULER=8102
BASE_JOBQUEUE=8101
BASE_GRAPHAI=8100
BASE_VITE=5173

PORT_EXPERTAGENT=$((BASE_EXPERTAGENT + (WORKTREE_INDEX * 10)))
PORT_MYVAULT=$((BASE_MYVAULT + (WORKTREE_INDEX * 10)))
PORT_MYSCHEDULER=$((BASE_MYSCHEDULER + (WORKTREE_INDEX * 10)))
PORT_JOBQUEUE=$((BASE_JOBQUEUE + (WORKTREE_INDEX * 10)))
PORT_GRAPHAI=$((BASE_GRAPHAI + (WORKTREE_INDEX * 10)))
PORT_VITE=$((BASE_VITE + WORKTREE_INDEX))

# .env.local ファイルを生成（インデックスも記録）
cat > .env.local <<EOF
# Auto-generated by setup-worktree.sh
# Worktree: $WORKTREE_NAME (index: $WORKTREE_INDEX)
# Generated at: $(date)
# ⚠️ DO NOT DELETE WORKTREE_INDEX - it ensures port stability

# Worktree metadata
WORKTREE_INDEX=$WORKTREE_INDEX

# expertAgent
EXPERTAGENT_PORT=$PORT_EXPERTAGENT
MYVAULT_PORT=$PORT_MYVAULT

# myVault
MYVAULT_SERVICE_PORT=$PORT_MYVAULT

# myscheduler
MYSCHEDULER_PORT=$PORT_MYSCHEDULER

# jobqueue
JOBQUEUE_PORT=$PORT_JOBQUEUE

# graphAiServer
GRAPHAI_PORT=$PORT_GRAPHAI

# myAgentDesk (SvelteKit)
VITE_PORT=$PORT_VITE
EOF

echo ""
echo "✅ Created .env.local with port assignments:"
echo "   - expertAgent: $PORT_EXPERTAGENT"
echo "   - myVault: $PORT_MYVAULT"
echo "   - myscheduler: $PORT_MYSCHEDULER"
echo "   - jobqueue: $PORT_JOBQUEUE"
echo "   - graphAiServer: $PORT_GRAPHAI"
echo "   - myAgentDesk: $PORT_VITE"

# .envへのシンボリックリンク作成
if [ -f "$MAIN_REPO/.env" ] && [ ! -e .env ]; then
    ln -s "$MAIN_REPO/.env" .env
    echo "✅ Created symlink: .env -> $MAIN_REPO/.env"
elif [ -e .env ]; then
    echo "✅ .env already exists (symlink or file)"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔐 myVault Directory Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Select myVault directory placement:"
echo "  1) Share data with develop branch (symlink myVault/data only)"
echo "     → Resource efficient, data shared, app code independent"
echo "  2) Independent copy in current worktree (PWD/myVault)"
echo "     → Fully isolated environment, safe for parallel testing"
echo "  3) Custom path (manual input)"
echo "     → Flexible, share with specific worktrees"
echo ""
read -p "Enter choice [1-3] (default: 1): " myvault_choice
myvault_choice=${myvault_choice:-1}

case $myvault_choice in
    1)
        # 共有モード（データディレクトリのみシンボリックリンク）
        if [ -d "$MAIN_REPO/myVault" ]; then
            # アプリケーションコードは実ディレクトリのまま維持
            # データディレクトリのみシンボリックリンク化
            if [ -d myVault/data ] && [ ! -L myVault/data ]; then
                rm -rf myVault/data
            fi
            if [ ! -e myVault/data ]; then
                ln -s "$MAIN_REPO/myVault/data" myVault/data
            fi
            echo "✅ Created symlink: myVault/data -> $MAIN_REPO/myVault/data"
            echo "   Note: Sharing myVault data with develop branch (app code is independent)."
        else
            echo "⚠️  $MAIN_REPO/myVault not found. Creating independent copy instead."
            mkdir -p myVault/data
        fi
        ;;
    2)
        # 独立モード（PWD）
        mkdir -p myVault/data
        if [ -f "$MAIN_REPO/myVault/data/myvault.db" ]; then
            cp "$MAIN_REPO/myVault/data/myvault.db" myVault/data/myvault.db
            echo "✅ Created independent myVault directory"
            echo "   Copied DB from: $MAIN_REPO/myVault/data/myvault.db"
            echo "   Note: Use ~/MySwiftAgent/scripts/sync-myvault-db.sh to sync updates."
        else
            echo "✅ Created independent myVault directory"
            echo "⚠️  Source DB not found. Starting with empty DB."
        fi
        ;;
    3)
        # カスタムモード（手動入力）
        read -p "Enter custom myVault path: " custom_myvault_path
        if [ -d "$custom_myvault_path" ]; then
            if [ -e myVault ]; then
                rm -rf myVault
            fi
            ln -s "$custom_myvault_path" myVault
            echo "✅ Created symlink: myVault -> $custom_myvault_path"
        else
            echo "❌ Path not found: $custom_myvault_path"
            echo "   Creating independent directory instead."
            mkdir -p myVault/data
        fi
        ;;
    *)
        echo "❌ Invalid choice. Creating independent directory."
        mkdir -p myVault/data
        ;;
esac

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔍 Langfuse Directory Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Select Langfuse directory placement:"
echo "  1) Share data with develop branch (symlink langfuse/data only)"
echo "     → Resource efficient, data shared, config files independent"
echo "  2) Independent copy in current worktree (PWD/langfuse)"
echo "     → Fully isolated environment, separate Docker instance"
echo "  3) Custom path (manual input)"
echo "     → Flexible, share with specific worktrees"
echo ""
read -p "Enter choice [1-3] (default: 1): " langfuse_choice
langfuse_choice=${langfuse_choice:-1}

case $langfuse_choice in
    1)
        # 共有モード（データディレクトリのみシンボリックリンク）
        if [ -d "$MAIN_REPO/langfuse" ]; then
            # アプリケーション設定ファイルは実ディレクトリのまま維持
            # データディレクトリ/docker-compose-dataのみシンボリックリンク化
            if [ -d langfuse/data ] && [ ! -L langfuse/data ]; then
                rm -rf langfuse/data
            fi
            if [ ! -e langfuse/data ] && [ -d "$MAIN_REPO/langfuse/data" ]; then
                ln -s "$MAIN_REPO/langfuse/data" langfuse/data
            fi
            if [ -d langfuse/docker-compose-data ] && [ ! -L langfuse/docker-compose-data ]; then
                rm -rf langfuse/docker-compose-data
            fi
            if [ ! -e langfuse/docker-compose-data ] && [ -d "$MAIN_REPO/langfuse/docker-compose-data" ]; then
                ln -s "$MAIN_REPO/langfuse/docker-compose-data" langfuse/docker-compose-data
            fi
            echo "✅ Created symlink: langfuse/data -> $MAIN_REPO/langfuse/data"
            echo "✅ Created symlink: langfuse/docker-compose-data -> $MAIN_REPO/langfuse/docker-compose-data"
            echo "   Note: Sharing Langfuse data with develop branch (config files are independent)."
        else
            echo "⚠️  $MAIN_REPO/langfuse not found. Creating independent copy instead."
            mkdir -p langfuse
        fi
        ;;
    2)
        # 独立モード（PWD）
        if [ -d "$MAIN_REPO/langfuse" ]; then
            # 設定ファイルのみコピー（データは除外）
            mkdir -p langfuse
            [ -f "$MAIN_REPO/langfuse/.env.example" ] && cp "$MAIN_REPO/langfuse/.env.example" langfuse/
            [ -f "$MAIN_REPO/langfuse/docker-compose.langfuse.yml" ] && cp "$MAIN_REPO/langfuse/docker-compose.langfuse.yml" langfuse/
            [ -f "$MAIN_REPO/langfuse/README.md" ] && cp "$MAIN_REPO/langfuse/README.md" langfuse/
            echo "✅ Created independent langfuse directory"
            echo "   Copied config files from: $MAIN_REPO/langfuse/"
            echo "   Note: You can start your own Langfuse instance here."
        else
            echo "⚠️  $MAIN_REPO/langfuse not found. Directory already exists in git."
            echo "✅ Using existing langfuse directory"
        fi
        ;;
    3)
        # カスタムモード（手動入力）
        read -p "Enter custom langfuse path: " custom_langfuse_path
        if [ -d "$custom_langfuse_path" ]; then
            if [ -e langfuse ]; then
                rm -rf langfuse
            fi
            ln -s "$custom_langfuse_path" langfuse
            echo "✅ Created symlink: langfuse -> $custom_langfuse_path"
        else
            echo "❌ Path not found: $custom_langfuse_path"
            echo "   Creating independent directory instead."
            mkdir -p langfuse
        fi
        ;;
    *)
        echo "❌ Invalid choice. Using existing directory."
        ;;
esac

# .env.local にセットアップ情報を追記
cat >> .env.local <<EOF

# Setup Configuration (for reference)
# myVault: $([ -L myVault ] && echo "Shared (symlink)" || echo "Independent")
# langfuse: $([ -L langfuse ] && echo "Shared (symlink)" || echo "Independent")
EOF

if [ -L myVault ]; then
    cat >> .env.local <<EOF
# Note: myVault is shared. Port settings above may not apply.
EOF
fi

if [ -L langfuse ]; then
    cat >> .env.local <<EOF
# Note: langfuse is shared. Port settings above may not apply.
EOF
fi

echo ""
echo "🎉 Worktree setup complete!"
echo ""
echo "📝 Next steps:"
echo "   1. Install dependencies:"
echo "      cd expertAgent && uv sync"
echo "      cd myAgentDesk && npm install"
echo ""
echo "   2. Start development servers:"
echo "      cd expertAgent && uv run uvicorn app.main:app --reload"
echo "      cd myAgentDesk && npm run dev"
echo ""
if [ -L myVault ]; then
    echo "   3. myVault: Shared with $MAIN_REPO/myVault"
    echo "      - Access via shared instance"
else
    echo "   3. myVault: Independent instance"
    echo "      - Start: cd myVault && uv run uvicorn app.main:app --reload"
    echo "      - Access: http://localhost:$PORT_MYVAULT"
fi
echo ""
if [ -L langfuse ]; then
    echo "   4. Langfuse: Shared with $MAIN_REPO/langfuse"
    echo "      - Access via shared instance at http://localhost:3001"
else
    echo "   4. Langfuse: Independent instance"
    echo "      - Start: cd langfuse && docker compose -f docker-compose.langfuse.yml --env-file .env up -d"
    echo "      - Access: http://localhost:3001 (or custom port if configured)"
fi
echo ""
echo "   5. Access services:"
echo "      - expertAgent: http://localhost:$PORT_EXPERTAGENT"
echo "      - myAgentDesk: http://localhost:$PORT_VITE"
