#!/bin/bash

# Setup Valkey for Worktree Environment
# Allocates unique port and creates isolated data directory for each worktree

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

# Port range for worktree Valkey instances
PORT_MIN=6380
PORT_MAX=6399

# Get project root
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Port registry file
PORTS_FILE="$PROJECT_ROOT/.valkey-ports"

# Print functions
print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Show usage
usage() {
    cat << EOF
Usage: $0 [OPTIONS]

Setup Valkey for worktree environment with isolated port and data directory.

Options:
    --port PORT     Specify port (default: auto-allocate from ${PORT_MIN}-${PORT_MAX})
    --help          Show this help message

Example:
    $0                    # Auto-allocate port
    $0 --port 6385        # Use specific port

Environment Variables:
    VALKEY_PORT    Override default port allocation
EOF
}

# Check if port is in use
check_port() {
    local port=$1
    if lsof -Pi :$port -sTCP:LISTEN -t >/dev/null 2>&1; then
        return 0  # Port is in use
    else
        return 1  # Port is free
    fi
}

# Find available port
find_available_port() {
    local port

    # Create port registry if it doesn't exist
    touch "$PORTS_FILE"

    # Try each port in range
    for port in $(seq $PORT_MIN $PORT_MAX); do
        # Skip if port is already in registry for another worktree
        if grep -q "^$port:" "$PORTS_FILE" 2>/dev/null; then
            continue
        fi

        # Check if port is actually free
        if ! check_port $port; then
            echo $port
            return 0
        fi
    done

    print_error "No available ports in range ${PORT_MIN}-${PORT_MAX}"
    return 1
}

# Allocate port for this worktree
allocate_port() {
    local requested_port=$1
    local worktree_name=$(basename "$PROJECT_ROOT")

    # Check if this worktree already has a port
    local existing_port=$(grep "^[0-9]*:$worktree_name$" "$PORTS_FILE" 2>/dev/null | cut -d: -f1)
    if [[ -n "$existing_port" ]]; then
        print_info "Worktree '$worktree_name' already has port $existing_port"
        echo $existing_port
        return 0
    fi

    # Use requested port or find available
    local port
    if [[ -n "$requested_port" ]]; then
        port=$requested_port
        if check_port $port; then
            print_error "Port $port is already in use"
            return 1
        fi
        if grep -q "^$port:" "$PORTS_FILE" 2>/dev/null; then
            print_error "Port $port is already allocated to another worktree"
            return 1
        fi
    else
        port=$(find_available_port)
        if [[ -z "$port" ]]; then
            return 1
        fi
    fi

    # Register port
    echo "$port:$worktree_name" >> "$PORTS_FILE"
    print_success "Allocated port $port for worktree '$worktree_name'"
    echo $port
}

# Detect if running in worktree
detect_worktree() {
    if [[ -f "$PROJECT_ROOT/.git" ]]; then
        # This is a worktree (has .git file instead of directory)
        return 0
    elif [[ -d "$PROJECT_ROOT/.git/worktrees" ]]; then
        # This is main repo with worktrees
        return 1
    else
        # Standard repository
        return 1
    fi
}

# Setup Valkey for worktree
setup_worktree_valkey() {
    local requested_port=$1

    print_info "Setting up Valkey for worktree environment..."

    # Detect worktree
    if ! detect_worktree; then
        print_warning "Not running in a worktree environment"
        print_info "This script is designed for git worktree environments"
    fi

    # Allocate port
    local port=$(allocate_port "$requested_port")
    if [[ -z "$port" ]]; then
        print_error "Failed to allocate port"
        exit 1
    fi

    # Create data directory
    local data_dir="$PROJECT_ROOT/valkey/data"
    mkdir -p "$data_dir"
    print_success "Created data directory: $data_dir"

    # Generate worktree-specific config
    local config_dir="$PROJECT_ROOT/valkey/config"
    local config_file="$config_dir/valkey.conf"

    if [[ ! -f "$config_file" ]]; then
        print_warning "Base config file not found, creating from template..."
        mkdir -p "$config_dir"

        cat > "$config_file" <<EOF
# Valkey Configuration for Worktree
# Auto-generated by setup-valkey-worktree.sh

# Network
bind 0.0.0.0
port $port
protected-mode no

# Persistence
save 900 1
save 300 10
save 60 10000
dir /data
dbfilename valkey.rdb

# Memory
maxmemory 256mb
maxmemory-policy allkeys-lru

# Logging
loglevel notice
logfile ""

# Snapshotting
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes

# Performance
tcp-backlog 511
timeout 0
tcp-keepalive 300

# Append Only File
appendonly no
EOF
        print_success "Created config file: $config_file"
    else
        # Update port in existing config
        if command -v sed &> /dev/null; then
            sed -i.bak "s/^port [0-9]*/port $port/" "$config_file"
            rm -f "$config_file.bak"
            print_success "Updated port to $port in config file"
        fi
    fi

    # Update .env if it exists
    local env_file="$PROJECT_ROOT/expertAgent/.env"
    if [[ -f "$env_file" ]]; then
        if grep -q "^VALKEY_URL=" "$env_file"; then
            sed -i.bak "s|^VALKEY_URL=.*|VALKEY_URL=redis://localhost:$port|" "$env_file"
            rm -f "$env_file.bak"
            print_success "Updated VALKEY_URL in expertAgent/.env"
        else
            echo "VALKEY_URL=redis://localhost:$port" >> "$env_file"
            print_success "Added VALKEY_URL to expertAgent/.env"
        fi
    fi

    # Summary
    echo ""
    print_success "Valkey worktree setup complete!"
    echo ""
    echo "Configuration:"
    echo "  Port:       $port"
    echo "  Data Dir:   $data_dir"
    echo "  Config:     $config_file"
    echo ""
    echo "To start Valkey:"
    echo "  export VALKEY_PORT=$port"
    echo "  ./scripts/dev-start.sh"
    echo ""
}

# Main
main() {
    local requested_port=""

    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            --port)
                requested_port=$2
                shift 2
                ;;
            --help|-h)
                usage
                exit 0
                ;;
            *)
                print_error "Unknown option: $1"
                usage
                exit 1
                ;;
        esac
    done

    # Use environment variable if set
    if [[ -z "$requested_port" && -n "$VALKEY_PORT" ]]; then
        requested_port=$VALKEY_PORT
    fi

    setup_worktree_valkey "$requested_port"
}

main "$@"
