name: Simple Test

on:
  workflow_dispatch:
    inputs:
      message:
        description: Test message
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.message }}"