name: Test Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      test_message:
        description: 'Test message'
        required: true
        type: string
        default: 'hello'

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "Message: ${{ github.event.inputs.test_message }}"